project_id = "baby-timer"

[functions.daily-summary]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.device-link-exchange]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.auth-user-created]
verify_jwt = false
